### ISSUE TITLE
sync api does not work

### ISSUE THREAD

**Issue by stephg** [devongovett/browserify-zlib#20]
Whenever i call sync methods which use `zlibBufferSync()`, I get:

```
# zlib (zlibBufferSync) elipses.txt 16384 {"level":6,"windowBits":15,"memLevel":8,"strategy":0} DeflateRaw -> InflateRaw
not ok 82 Error: buffer error:
  ---
    operator: error
    expected: undefined
    actual:   { [Error: buffer error: ] errno: -5, code: 'Z_BUF_ERROR' }
    stack:
      Error: buffer error:
        at Zlib._binding.onerror (/Users/stephg/Development/checkpad/browserify-zlib/src/index.js:364:17)
        at Zlib._error (/Users/stephg/Development/checkpad/browserify-zlib/src/binding.js:229:8)
        at Zlib._write (/Users/stephg/Development/checkpad/browserify-zlib/src/binding.js:187:10)
        at Zlib.writeSync (/Users/stephg/Development/checkpad/browserify-zlib/src/binding.js:136:15)
        at InflateRaw.Zlib._processChunk (/Users/stephg/Development/checkpad/browserify-zlib/src/index.js:520:31)
        at Object.zlibBufferSync (/Users/stephg/Development/checkpad/browserify-zlib/src/index.js:235:17)
        at Test.<anonymous> (/Users/stephg/Development/checkpad/browserify-zlib/test/test-zlib.js:218:37)
        at Test.bound [as _cb] (/Users/stephg/Development/checkpad/browserify-zlib/node_modules/tape/lib/test.js:60:32)
        at Test.run (/Users/stephg/Development/checkpad/browserify-zlib/node_modules/tape/lib/test.js:74:14)
        at Test.bound [as run] (/Users/stephg/Development/checkpad/browserify-zlib/node_modules/tape/lib/test.js:60:32)
  ...
```

This is the test:
https://github.com/factisresearch/browserify-zlib/commit/734fbaba0538b455719018168fc89dccab96e357

**Comment by rbuels** [comment]
Is this still an issue?  #18 claims that this was fixed by its merge.

**Comment by stephg** [comment]
Yes, looks like this is resolved by #18.
